name: Test

on:
  push:
    branches: [main]

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: mydb-test
        ports:
          - 5431:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: run unit tests
        run: npm run test:cov
      - name: run e2e tests
        run: npm run test:e2e
